export const CHARACTER_ALL_REQUEST = 'CHARACTER_ALL_REQUEST';
export const CHARACTER_ALL_SUCCESS = 'CHARACTER_ALL_SUCCESS';
export const CHARACTER_ALL_FAIL = 'CHARACTER_ALL_FAIL';
export const CHARACTER_ONE_REQUEST = 'CHARACTER_ONE_REQUEST';
export const CHARACTER_ONE_SUCCESS = 'CHARACTER_ONE_SUCCESS';
export const CHARACTER_ONE_FAIL = 'CHARACTER_ONE_FAIL';
